print("Enter your name : ")
x = input()
print("Enter your ID")
y = input()
print("Enter your section")
z = input()
print()
print()
print("=====================================OUTPUT=====================================")
print("================================================================================")
print("Hello ! >>>>  " + "{ Name : " + x +" ID Student : "+ y +" Section : " + z + "}")
print("================================================================================")